name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  cypress_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
    
      - name: Install dependencies
        run: npm ci
        
      - name: Start the server
        run: nohup npm run start-server &

      - name: Start frontend
        run: nohup npm run start-frontend &

      - name: Wait for frontend to become available
        run: |
          echo "Waiting for frontend to launch on port 5173..."
          while ! nc -z localhost 5173; do   
            sleep 1 # wait for 1 second before check again
          done

      - name: Install Cypress dependencies
        run: cd ./cypress && npm ci

      - name: Run Cypress tests
        run: cd ./cypress && npm run test
        env:
          CYPRESS_BASE_URL: http://localhost:5173

  deploy:
    needs: cypress_tests
    runs-on: ubuntu-latest
    steps:
      - name: Doing a deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Deploying to the server"
            source /root/.nvm/nvm.sh
            nvm use v20.12.2
            echo "Checking node and npm versions"
            node -v
            npm -v
            cd /var/www/Globetrotter
            git pull
            rm -r cypress
            cd /var/www/Globetrotter/Client           
            npm ci
            rm -r dist
            npm run build
            cd /var/www/Globetrotter/Server
            rm -r dist
            cp -r /var/www/Globetrotter/Client/dist .
            pm2 delete dotnetBio
            pm2 start --name dotnetBio "dotnet run"
